### ISSUE TITLE
Update Bomber Icon shortcode usage

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/aerospace_wp#54]
Currently, the site is set up to [include the Bomber Icon automatically](https://github.com/CSIS-iLab/aerospace_wp/blob/master/wp-content/themes/aerospace/inc/template-functions.php#L137-L153) at the end of the post content unless the program has checked a meta box that says to not include it. The new Gutenberg blocks mean that including the icon will result in it being separated on its own line below the content as opposed to on the same line as the last bit of text content.

To fix this, we need to rework this feature so that the program must manually include the Bomber shortcode when they want to use it.

## To-dos
- [ ] Remove filter on `the_content`. Relevant function [here](https://github.com/CSIS-iLab/aerospace_wp/blob/master/wp-content/themes/aerospace/inc/template-functions.php#L137-L153).
- [ ] Remove custom post meta box for `_post_disable_post_bottom_icon` on all relevant post types
- [ ] Look at possibility of adding a button to the toolbar to insert the `[aircraft]` shortcode when clicked. Check-out [this tutorial](https://wordpress.org/gutenberg/handbook/designers-developers/developers/tutorials/format-api/) from the documentation.

**Comment by dlousa92** [comment]
An update on this issue, I just created a pull request for the first two checkboxes, below is an update on the last checkbox

I'm able to add a button into the toolbar using the format API so that's awesome! Screenshot below,
![Screen Shot 2019-04-15 at 11 11 06 AM](https://user-images.githubusercontent.com/30706065/56143825-3f542b00-5f6f-11e9-9878-579bf884a4c8.png)

However the biggest hurdle I'm having right now is how to add the shortcode into that button. There's a few methods in rich-text that are possible to use, linked [here](https://wordpress.org/gutenberg/handbook/designers-developers/developers/packages/packages-rich-text/). I've been experimenting with applyFormat and toggleFormat. These do work in the sense that I'm able to insert code that's similar to the shortcode as per the screenshot below,
![Screen Shot 2019-04-15 at 11 11 18 AM](https://user-images.githubusercontent.com/30706065/56143857-4f6c0a80-5f6f-11e9-8862-9879c4c577a2.png)

The main problem is I'm unable to set an src link to the image using these methods. I can set a background url for this element with the bomber image in css, however I know that's kind of hacky.

Another possible solution I've found is that perhaps it's possible to create a Gutenberg block that would be the bomber icon and then making this block inline with css. Here is a [link](https://github.com/WordPress/gutenberg/issues/10235) to an issue on the gutenberg repository that references this.
